package paquete.model;
// Generated 02-dic-2015 14:11:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Contacts generated by hbm2java
 */
@Entity
@Table(name="contacts"
    ,catalog="miscontactos"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Contacts  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String phone;
     private String pictureUrl;
     private int groupId;
     private String groupName;
     private Set<Emails> emailses = new HashSet<Emails>(0);
     //private Set<Emails> emailses;

    public Contacts() {
    }

	
    public Contacts(String name, String phone, String pictureUrl, int groupId) {
        this.name = name;
        this.phone = phone;
        this.pictureUrl = pictureUrl;
        this.groupId = groupId;
    }
    public Contacts(String name, String phone, String pictureUrl, int groupId, Set<Emails> emailses) {
       this.name = name;
       this.phone = phone;
       this.pictureUrl = pictureUrl;
       this.groupId = groupId;
       this.emailses = emailses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="phone", nullable=false, length=9)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="picture_url", nullable=false)
    public String getPictureUrl() {
        return this.pictureUrl;
    }
    
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl;
    }

    
    @Column(name="group_id", nullable=false)
    public int getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="contacts")
    //@OneToMany(cascade = CascadeType.ALL, mappedBy="contacts")
    public Set<Emails> getEmailses() {
        return this.emailses;
    }
    
    public void setEmailses(Set<Emails> emailses) {
        this.emailses = emailses;
    }




}


