package paquete.model;
// Generated 02-dic-2015 14:11:15 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Emails generated by hbm2java
 */
@Entity
@Table(name="emails"
    ,catalog="miscontactos"
)
public class Emails  implements java.io.Serializable {


     private Integer id;
     private Contacts contacts;
     private String address;

    public Emails() {
    }

    public Emails(Contacts contacts, String address) {
       this.contacts = contacts;
       this.address = address;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    //@ManyToOne
    @JoinColumn(name="contact_id", nullable=false)
    public Contacts getContacts() {
        return this.contacts;
    }
    
    public void setContacts(Contacts contacts) {
        this.contacts = contacts;
    }

    
    @Column(name="address", nullable=false)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


