package paquete.model;
// Generated 02-dic-2015 14:11:15 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Links generated by hbm2java
 */
@Entity
@Table(name="links"
    ,catalog="miscontactos"
)
public class Links  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String link;

    public Links() {
    }

    public Links(String name, String link) {
       this.name = name;
       this.link = link;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="link", nullable=false)
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }




}


